[package]
name = "gfatk"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfa = "0.10"
bstr = "0.2"
clap = { version = "3.1.5", features = ["cargo"] }
petgraph = "0.6.0"
byteorder = "1.4.3"
indexmap = "1.7.0"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
itertools = "0.10.2"
anyhow = "1.0"
thiserror = "1.0"
atty = "0.2"