[package]
name = "gfatk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfa = "0.10"
bstr = "0.2"
clap = "2.33.3"
petgraph = "0.6.0"