[package]
name = "gfatk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfa = "0.10"
bstr = "0.2"
clap = { version = "3.0.10", features = ["derive"] }
petgraph = "0.6.0"
byteorder = "1.4.3"
indexmap = "1.7.0"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
itertools = "0.10.2"
#genome-graph = "0.6.2"
#handlegraph = "0.6.0"